import Link from "next/link";
import { LegalShell } from "@/components/legal-shell";

export const metadata = {
  title: "Privacy Policy — ThreadLens",
};

export default function PrivacyPolicyPage() {
  return (
    <LegalShell
      title={
        <>
          Privacy <em>Policy</em>
        </>
      }
      meta={
        <>
          <span className="pill">Effective · April 20, 2026</span>
          <span className="sep"></span>
          <span>Operated by Indo Berkah Solution</span>
          <span className="sep"></span>
          <span>~6 min read</span>
        </>
      }
    >
      <h2>
        <span className="num">01</span>About ThreadLens
      </h2>
      <p>
        ThreadLens (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;the service&rdquo;) is an analytics application for
        personal Threads accounts. We pull public data and insights from Threads accounts that you voluntarily connect
        via Meta&apos;s official OAuth flow, and present them in a dashboard alongside AI-generated analysis.
      </p>

      <h2>
        <span className="num">02</span>Data we collect
      </h2>
      <p>When you register and connect a Threads account, we store:</p>
      <ul>
        <li>
          <b>ThreadLens account:</b> email address and password (hashed with bcrypt — we never store passwords in plain
          text).
        </li>
        <li>
          <b>Threads profile:</b> Threads user ID, username, display name, and profile picture URL.
        </li>
        <li>
          <b>Threads access token:</b> encrypted with AES-256-GCM before storage. The token is used solely to call the
          Threads API on your behalf.
        </li>
        <li>
          <b>Post content:</b> text, media URL, permalink, timestamp, and media type from posts on your Threads account.
        </li>
        <li>
          <b>Insights:</b> per-post counts of views, likes, replies, reposts, quotes, shares, plus account-level metrics
          such as follower count.
        </li>
        <li>
          <b>AI analysis output:</b> the text generated by the LLM whenever you run a performance or pattern analysis.
        </li>
      </ul>

      <h2>
        <span className="num">03</span>How we use the data
      </h2>
      <ul>
        <li>To render your Threads analytics dashboard.</li>
        <li>To send post metadata as prompts to an LLM provider (OpenRouter) so it can produce analysis.</li>
        <li>To store analysis history so you can review it later.</li>
        <li>To maintain the connection (refresh access tokens) for as long as your Threads account is linked.</li>
      </ul>
      <div className="callout">
        <svg width="18" height="18" viewBox="0 0 16 16" fill="none">
          <path
            d="M8 1.5l5.5 2.5v4.6c0 3.2-2.2 6.1-5.5 7.1-3.3-1-5.5-3.9-5.5-7.1V4L8 1.5z"
            stroke="currentColor"
            strokeWidth="1.4"
          />
          <path
            d="M5.5 8l1.8 1.8L10.8 6.4"
            stroke="currentColor"
            strokeWidth="1.4"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
        <div>
          <b>We do not sell your data.</b>
          <p>
            We do not use your data for advertising, and we do not share it with any third parties beyond the technical
            processors listed below.
          </p>
        </div>
      </div>

      <h2>
        <span className="num">04</span>Third-party processors
      </h2>
      <ul>
        <li>
          <b>Supabase</b> — database where all data is stored.
        </li>
        <li>
          <b>Vercel</b> — application hosting.
        </li>
        <li>
          <b>Meta / Threads Graph API</b> — source of Threads data (you authorize access through OAuth).
        </li>
        <li>
          <b>OpenRouter and the chosen LLM provider</b> — process analysis prompts. Post content (text and metrics) is
          sent to the LLM provider when you trigger an analysis.
        </li>
      </ul>

      <h2>
        <span className="num">05</span>Storage and security
      </h2>
      <ul>
        <li>Threads access tokens are encrypted before being stored.</li>
        <li>Admin passwords are hashed with bcrypt at cost 12.</li>
        <li>Database access is server-side only, using a service role.</li>
        <li>Login sessions use httpOnly cookies signed as JWTs.</li>
        <li>All traffic is served over TLS 1.3.</li>
      </ul>

      <h2>
        <span className="num">06</span>Your rights &amp; data deletion
      </h2>
      <p>You can remove your data at any time:</p>
      <ul>
        <li>
          <b>Disconnect a Threads account</b> from the <Link href="/settings">Settings</Link> page — all posts,
          insights, and analysis history for that account will be permanently deleted.
        </li>
        <li>
          <b>Delete your ThreadLens account</b> — email us (address below) with the subject &ldquo;Delete
          account&rdquo;. Data will be removed within 7 days.
        </li>
        <li>
          <b>Requests from Meta:</b> if you revoke the app&apos;s permission from your Threads settings, Meta sends a
          signed request to our Data Deletion Callback endpoint, and we automatically delete the corresponding data.
        </li>
      </ul>
      <p style={{ marginTop: 8 }}>
        <Link href="/data-deletion">Read the full data deletion instructions →</Link>
      </p>

      <h2>
        <span className="num">07</span>Cookies
      </h2>
      <p>We use only essential cookies:</p>
      <ul>
        <li>
          <code>threadlens_session</code> — login session (httpOnly, signed JWT).
        </li>
        <li>
          <code>threadlens_active_account</code> — currently selected Threads account in the switcher.
        </li>
        <li>
          <code>threads_oauth_state</code> — short-lived, used to verify the OAuth state parameter.
        </li>
      </ul>
      <p>
        No tracking cookies, no third-party advertising cookies. <Link href="/cookies">See our full cookie policy →</Link>
      </p>

      <h2>
        <span className="num">08</span>Children
      </h2>
      <p>The service is intended for users aged 13 and over, in line with Threads / Meta&apos;s terms of service.</p>

      <h2>
        <span className="num">09</span>Changes to this policy
      </h2>
      <p>
        This policy may change from time to time. The &ldquo;effective date&rdquo; above will be updated whenever it
        does. Material changes will be communicated by email to the address on file.
      </p>

      <h2>
        <span className="num">10</span>Contact
      </h2>
      <p>For questions, data access or deletion requests, or privacy concerns:</p>
      <p>
        <a href="mailto:bhskindatabase@gmail.com">bhskindatabase@gmail.com</a>
        <br />
        Indo Berkah Solution · Jakarta, Indonesia
      </p>
    </LegalShell>
  );
}
